version: 0.2

phases:
  install:
    commands:
      - echo "Updating apt and installing PHP 8.3 with extensions"
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:ondrej/php -y
      - apt-get update -y
      - apt-get install -y php8.3 php8.3-cli php8.3-mbstring php8.3-xml php8.3-mysql php8.3-curl php8.3-bcmath php8.3-zip php8.3-gd php8.3-common php8.3-readline php8.3-intl php8.3-pgsql unzip git curl zip
      - update-alternatives --set php /usr/bin/php8.3
      - php -v
  pre_build:
    commands:
      - echo "Installing Composer"
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - echo "Installing dependencies with Composer"
      - composer install --no-dev --optimize-autoloader
artifacts:
  files:
    - '**/*'
